<script lang="ts">
	import { onMount } from 'svelte';
	import { site } from '$lib/config/site';
	import {
		IconDownload,
		IconClipboard,
		IconRefresh,
		IconPlus,
		IconTrash,
		IconCheck
	} from '@tabler/icons-svelte';

	const DRAFT_KEY = 'nyx-admin-draft';

	type SiteShape = typeof site;

	let data = $state<SiteShape>(structuredClone(site) as SiteShape);
	let copied = $state(false);
	let openSection = $state<string | null>('identity');

	onMount(() => {
		const draft = localStorage.getItem(DRAFT_KEY);
		if (draft) {
			try {
				data = JSON.parse(draft);
			} catch {
				console.warn('Invalid draft in localStorage, ignoring');
			}
		}
	});

	$effect(() => {
		localStorage.setItem(DRAFT_KEY, JSON.stringify(data));
	});

	function resetDraft() {
		if (!confirm('Reset all fields to the current site.ts? Your draft will be lost.')) return;
		localStorage.removeItem(DRAFT_KEY);
		data = structuredClone(site) as SiteShape;
	}

	function generateTs(d: SiteShape): string {
		const body = JSON.stringify(d, null, '\t');
		return `// Generated by /admin on ${new Date().toISOString().slice(0, 10)}.
// Drop this file into src/lib/config/site.ts and commit to deploy.

export interface PetPhoto {
	url: string;
	alt: string;
}

export interface Pet {
	name: string;
	heading: string;
	photos: PetPhoto[];
}

export interface ExperienceEntry {
	company: string;
	role: string;
	url: string;
	logoUrl: string;
	logoAlt: string;
	startDate: string;
	endDate?: string;
	details?: string;
	logoScale?: number;
}

export interface NavItem {
	title: string;
	href: string;
	external?: boolean;
}

export const site = ${body};

export type SiteConfig = typeof site;
`;
	}

	async function copyToClipboard() {
		const ts = generateTs(data);
		await navigator.clipboard.writeText(ts);
		copied = true;
		setTimeout(() => (copied = false), 1500);
	}

	function download() {
		const ts = generateTs(data);
		const blob = new Blob([ts], { type: 'text/typescript' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = 'site.ts';
		a.click();
		URL.revokeObjectURL(url);
	}

	function addExperience() {
		data.experience = [
			...data.experience,
			{
				company: '',
				role: '',
				url: '',
				logoUrl: '/logos/placeholder.svg',
				logoAlt: '',
				startDate: '',
				details: ''
			}
		];
	}

	function removeExperience(i: number) {
		data.experience = data.experience.filter((_, idx) => idx !== i);
	}

	function addNav(target: 'main' | 'more') {
		data.nav[target] = [...data.nav[target], { title: '', href: '' }];
	}

	function removeNav(target: 'main' | 'more', i: number) {
		data.nav[target] = data.nav[target].filter((_, idx) => idx !== i);
	}

	function addParagraph() {
		data.about.paragraphs = [...data.about.paragraphs, ''];
	}

	function removeParagraph(i: number) {
		data.about.paragraphs = data.about.paragraphs.filter((_, idx) => idx !== i);
	}

	function ensurePet() {
		if (!data.about.pet) {
			data.about.pet = { name: 'pet', heading: 'My Pet', photos: [] };
		}
	}

	function removePet() {
		data.about.pet = null;
	}

	function addPetPhoto() {
		if (!data.about.pet) ensurePet();
		data.about.pet!.photos = [...data.about.pet!.photos, { url: '', alt: '' }];
	}

	function removePetPhoto(i: number) {
		if (!data.about.pet) return;
		data.about.pet.photos = data.about.pet.photos.filter((_, idx) => idx !== i);
	}

	function toggleSection(name: string) {
		openSection = openSection === name ? null : name;
	}

	const sections = [
		{ id: 'identity', label: 'Identity' },
		{ id: 'hero', label: 'Hero' },
		{ id: 'about', label: 'About' },
		{ id: 'pics', label: 'Pics' },
		{ id: 'socials', label: 'Socials' },
		{ id: 'experience', label: 'Experience' },
		{ id: 'nav', label: 'Navigation' },
		{ id: 'brand', label: 'Branding' }
	];
</script>

<svelte:head>
	<title>Admin | {data.identity.name}</title>
</svelte:head>

<div class="mx-auto max-w-4xl px-4 py-8">
	<header class="mb-8 flex flex-wrap items-end justify-between gap-4">
		<div>
			<h1 class="text-3xl font-bold">Admin</h1>
			<p class="text-subtext0 mt-1 text-sm">
				Dev-only editor for <code class="text-accent">src/lib/config/site.ts</code>. Drafts
				autosave to localStorage. Export when ready.
			</p>
		</div>
		<div class="flex flex-wrap items-center gap-2">
			<button
				onclick={copyToClipboard}
				class="bg-surface0 hover:bg-surface1 text-text inline-flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors"
			>
				{#if copied}<IconCheck size={16} class="text-green" />Copied!{:else}<IconClipboard
						size={16}
					/>Copy TS{/if}
			</button>
			<button
				onclick={download}
				class="bg-accent/80 hover:bg-accent text-base inline-flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors"
			>
				<IconDownload size={16} />Download site.ts
			</button>
			<button
				onclick={resetDraft}
				class="text-subtext0 hover:text-red inline-flex items-center gap-2 px-2 py-2 text-sm transition-colors"
				title="Discard draft"
			>
				<IconRefresh size={16} />
			</button>
		</div>
	</header>

	<div class="space-y-3">
		{#each sections as section (section.id)}
			{@const open = openSection === section.id}
			<section class="border-surface0 bg-base rounded-lg border">
				<button
					onclick={() => toggleSection(section.id)}
					class="hover:bg-surface0/40 flex w-full items-center justify-between p-4 text-left"
				>
					<h2 class="text-text text-lg font-semibold">{section.label}</h2>
					<span class="text-subtext0 text-xs">{open ? '−' : '+'}</span>
				</button>
				{#if open}
					<div class="border-surface0 space-y-3 border-t p-4">
						{#if section.id === 'identity'}
							<div class="grid grid-cols-2 gap-3">
								<label class="block">
									<span class="text-subtext0 mb-1 block text-xs">Full name</span>
									<input type="text" bind:value={data.identity.name} class="admin-input" />
								</label>
								<label class="block">
									<span class="text-subtext0 mb-1 block text-xs">Handle</span>
									<input type="text" bind:value={data.identity.handle} class="admin-input" />
								</label>
								<label class="block">
									<span class="text-subtext0 mb-1 block text-xs">First name</span>
									<input type="text" bind:value={data.identity.firstName} class="admin-input" />
								</label>
								<label class="block">
									<span class="text-subtext0 mb-1 block text-xs">Last name</span>
									<input type="text" bind:value={data.identity.lastName} class="admin-input" />
								</label>
								<label class="col-span-2 block">
									<span class="text-subtext0 mb-1 block text-xs">Site URL (production)</span>
									<input type="url" bind:value={data.identity.url} class="admin-input" />
								</label>
								<label class="col-span-2 block">
									<span class="text-subtext0 mb-1 block text-xs">Job title</span>
									<input type="text" bind:value={data.identity.jobTitle} class="admin-input" />
								</label>
								<label class="col-span-2 block">
									<span class="text-subtext0 mb-1 block text-xs">SEO description</span>
									<textarea
										bind:value={data.identity.description}
										class="admin-input min-h-[3rem]"
										rows="2"
									></textarea>
								</label>
								<label class="block">
									<span class="text-subtext0 mb-1 block text-xs">Works for (company name)</span>
									<input
										type="text"
										bind:value={data.identity.seo.worksFor.name}
										class="admin-input"
									/>
								</label>
								<label class="block">
									<span class="text-subtext0 mb-1 block text-xs">Works for (URL)</span>
									<input
										type="url"
										bind:value={data.identity.seo.worksFor.url}
										class="admin-input"
									/>
								</label>
								<label class="block">
									<span class="text-subtext0 mb-1 block text-xs">City</span>
									<input
										type="text"
										bind:value={data.identity.seo.location.city}
										class="admin-input"
									/>
								</label>
								<label class="block">
									<span class="text-subtext0 mb-1 block text-xs">Region</span>
									<input
										type="text"
										bind:value={data.identity.seo.location.region}
										class="admin-input"
									/>
								</label>
								<label class="block">
									<span class="text-subtext0 mb-1 block text-xs">Country</span>
									<input
										type="text"
										bind:value={data.identity.seo.location.country}
										class="admin-input"
									/>
								</label>
								<label class="block">
									<span class="text-subtext0 mb-1 block text-xs">Birth date (YYYY-MM-DD)</span>
									<input
										type="text"
										bind:value={data.identity.seo.birthDate}
										class="admin-input"
									/>
								</label>
							</div>
						{:else if section.id === 'hero'}
							<label class="block">
								<span class="text-subtext0 mb-1 block text-xs">Greeting</span>
								<input type="text" bind:value={data.hero.greeting} class="admin-input" />
							</label>
							<label class="block">
								<span class="text-subtext0 mb-1 block text-xs">Bio (shows on landing page)</span>
								<textarea
									bind:value={data.hero.bio}
									class="admin-input min-h-[6rem]"
									rows="4"
								></textarea>
							</label>
							<label class="block">
								<span class="text-subtext0 mb-1 block text-xs"
									>Easter-egg parens (optional — null to hide)</span
								>
								<input
									type="text"
									value={data.hero.easterEggParens ?? ''}
									oninput={(e) =>
										(data.hero.easterEggParens =
											(e.target as HTMLInputElement).value || null)}
									class="admin-input"
								/>
							</label>
						{:else if section.id === 'about'}
							<div class="grid grid-cols-2 gap-3">
								<label class="block">
									<span class="text-subtext0 mb-1 block text-xs">Page title</span>
									<input type="text" bind:value={data.about.pageTitle} class="admin-input" />
								</label>
								<label class="block">
									<span class="text-subtext0 mb-1 block text-xs">Heading</span>
									<input type="text" bind:value={data.about.heading} class="admin-input" />
								</label>
								<label class="col-span-2 block">
									<span class="text-subtext0 mb-1 block text-xs">Avatar URL</span>
									<input type="text" bind:value={data.about.avatarUrl} class="admin-input" />
								</label>
								<label class="col-span-2 block">
									<span class="text-subtext0 mb-1 block text-xs">Avatar alt text</span>
									<input type="text" bind:value={data.about.avatarAlt} class="admin-input" />
								</label>
								<label class="col-span-2 block">
									<span class="text-subtext0 mb-1 block text-xs">Intro</span>
									<textarea
										bind:value={data.about.intro}
										class="admin-input min-h-[4rem]"
										rows="2"
									></textarea>
								</label>
							</div>

							<div>
								<div class="mb-1 flex items-center justify-between">
									<span class="text-subtext0 text-xs">Paragraphs</span>
									<button
										onclick={addParagraph}
										class="text-accent inline-flex items-center gap-1 text-xs"
									>
										<IconPlus size={12} /> Add
									</button>
								</div>
								<div class="space-y-2">
									{#each data.about.paragraphs as _, i (i)}
										<div class="flex items-start gap-2">
											<textarea
												bind:value={data.about.paragraphs[i]}
												class="admin-input min-h-[4rem] flex-1"
												rows="2"
											></textarea>
											<button
												onclick={() => removeParagraph(i)}
												class="text-subtext0 hover:text-red mt-1"
												aria-label="Remove paragraph"
											>
												<IconTrash size={14} />
											</button>
										</div>
									{/each}
								</div>
							</div>

							<label class="block">
								<span class="text-subtext0 mb-1 block text-xs">Hobbies / outro text</span>
								<textarea
									bind:value={data.about.hobbiesText}
									class="admin-input min-h-[3rem]"
									rows="2"
								></textarea>
							</label>

							<label class="flex items-center gap-2 text-sm">
								<input type="checkbox" bind:checked={data.about.showEmailButton} />
								<span>Show email contact button</span>
							</label>

							<div class="border-surface0 border-t pt-3">
								<div class="mb-2 flex items-center justify-between">
									<span class="text-subtext0 text-xs">Pet block (optional)</span>
									{#if data.about.pet}
										<button
											onclick={removePet}
											class="text-subtext0 hover:text-red text-xs">Remove pet</button
										>
									{:else}
										<button onclick={ensurePet} class="text-accent text-xs">+ Add pet</button>
									{/if}
								</div>
								{#if data.about.pet}
									<div class="grid grid-cols-2 gap-3">
										<label class="block">
											<span class="text-subtext0 mb-1 block text-xs">Pet name (for anchor)</span>
											<input
												type="text"
												bind:value={data.about.pet.name}
												class="admin-input"
											/>
										</label>
										<label class="block">
											<span class="text-subtext0 mb-1 block text-xs">Heading</span>
											<input
												type="text"
												bind:value={data.about.pet.heading}
												class="admin-input"
											/>
										</label>
									</div>
									<div class="mt-2 space-y-2">
										<div class="flex items-center justify-between">
											<span class="text-subtext0 text-xs">Photos</span>
											<button
												onclick={addPetPhoto}
												class="text-accent inline-flex items-center gap-1 text-xs"
											>
												<IconPlus size={12} /> Add photo
											</button>
										</div>
										{#each data.about.pet.photos as _, i (i)}
											<div class="grid grid-cols-[1fr_1fr_auto] items-center gap-2">
												<input
													type="text"
													bind:value={data.about.pet.photos[i].url}
													placeholder="URL"
													class="admin-input"
												/>
												<input
													type="text"
													bind:value={data.about.pet.photos[i].alt}
													placeholder="Alt text"
													class="admin-input"
												/>
												<button
													onclick={() => removePetPhoto(i)}
													class="text-subtext0 hover:text-red"
													aria-label="Remove photo"
												>
													<IconTrash size={14} />
												</button>
											</div>
										{/each}
									</div>
								{/if}
							</div>
						{:else if section.id === 'pics'}
							<label class="block">
								<span class="text-subtext0 mb-1 block text-xs">Page title</span>
								<input type="text" bind:value={data.pics.pageTitle} class="admin-input" />
							</label>
							<label class="block">
								<span class="text-subtext0 mb-1 block text-xs">Heading</span>
								<input type="text" bind:value={data.pics.heading} class="admin-input" />
							</label>
							<label class="block">
								<span class="text-subtext0 mb-1 block text-xs">Description</span>
								<textarea
									bind:value={data.pics.description}
									class="admin-input"
									rows="2"
								></textarea>
							</label>
						{:else if section.id === 'socials'}
							<div class="grid grid-cols-1 gap-3 sm:grid-cols-2">
								{#each ['github', 'linkedin', 'x', 'bluesky', 'instagram', 'wakatime', 'calcom'] as key (key)}
									<label class="block">
										<span class="text-subtext0 mb-1 block text-xs capitalize">{key}</span>
										<input
											type="url"
											bind:value={data.socials[key as keyof typeof data.socials]}
											placeholder="Full URL"
											class="admin-input"
										/>
									</label>
								{/each}
							</div>
						{:else if section.id === 'experience'}
							<div class="mb-2 flex items-center justify-between">
								<span class="text-subtext0 text-xs"
									>{data.experience.length} entries</span
								>
								<button
									onclick={addExperience}
									class="text-accent inline-flex items-center gap-1 text-xs"
								>
									<IconPlus size={12} /> Add experience
								</button>
							</div>
							<div class="space-y-4">
								{#each data.experience as _, i (i)}
									<div class="border-surface0 rounded border p-3">
										<div class="mb-2 flex items-center justify-between">
											<span class="text-subtext0 text-xs">#{i + 1}</span>
											<button
												onclick={() => removeExperience(i)}
												class="text-subtext0 hover:text-red"
												aria-label="Remove entry"
											>
												<IconTrash size={14} />
											</button>
										</div>
										<div class="grid grid-cols-2 gap-2">
											<label class="block">
												<span class="text-subtext0 mb-1 block text-xs">Company</span>
												<input
													type="text"
													bind:value={data.experience[i].company}
													class="admin-input"
												/>
											</label>
											<label class="block">
												<span class="text-subtext0 mb-1 block text-xs">Role</span>
												<input
													type="text"
													bind:value={data.experience[i].role}
													class="admin-input"
												/>
											</label>
											<label class="col-span-2 block">
												<span class="text-subtext0 mb-1 block text-xs">Company URL</span>
												<input
													type="url"
													bind:value={data.experience[i].url}
													class="admin-input"
												/>
											</label>
											<label class="block">
												<span class="text-subtext0 mb-1 block text-xs">Logo URL</span>
												<input
													type="text"
													bind:value={data.experience[i].logoUrl}
													class="admin-input"
												/>
											</label>
											<label class="block">
												<span class="text-subtext0 mb-1 block text-xs">Logo alt</span>
												<input
													type="text"
													bind:value={data.experience[i].logoAlt}
													class="admin-input"
												/>
											</label>
											<label class="block">
												<span class="text-subtext0 mb-1 block text-xs"
													>Start date (YYYY-MM-DD)</span
												>
												<input
													type="text"
													bind:value={data.experience[i].startDate}
													class="admin-input"
												/>
											</label>
											<label class="block">
												<span class="text-subtext0 mb-1 block text-xs"
													>End date (blank = current)</span
												>
												<input
													type="text"
													value={data.experience[i].endDate ?? ''}
													oninput={(e) =>
														(data.experience[i].endDate =
															(e.target as HTMLInputElement).value || undefined)}
													class="admin-input"
												/>
											</label>
											<label class="col-span-2 block">
												<span class="text-subtext0 mb-1 block text-xs">Details</span>
												<textarea
													bind:value={data.experience[i].details}
													class="admin-input"
													rows="2"
												></textarea>
											</label>
										</div>
									</div>
								{/each}
							</div>
						{:else if section.id === 'nav'}
							{#each ['main', 'more'] as target (target)}
								{@const tKey = target as 'main' | 'more'}
								<div class="mb-3">
									<div class="mb-2 flex items-center justify-between">
										<span class="text-text text-sm font-medium capitalize"
											>{target} nav ({data.nav[tKey].length})</span
										>
										<button
											onclick={() => addNav(tKey)}
											class="text-accent inline-flex items-center gap-1 text-xs"
										>
											<IconPlus size={12} /> Add
										</button>
									</div>
									<div class="space-y-2">
										{#each data.nav[tKey] as _, i (i)}
											<div
												class="grid grid-cols-[1fr_1.5fr_auto_auto] items-center gap-2"
											>
												<input
													type="text"
													bind:value={data.nav[tKey][i].title}
													placeholder="Title"
													class="admin-input"
												/>
												<input
													type="text"
													bind:value={data.nav[tKey][i].href}
													placeholder="/path or https://..."
													class="admin-input"
												/>
												<label class="text-subtext0 inline-flex items-center gap-1 text-xs">
													<input
														type="checkbox"
														checked={data.nav[tKey][i].external ?? false}
														onchange={(e) =>
															(data.nav[tKey][i].external = (
																e.target as HTMLInputElement
															).checked)}
													/>
													ext
												</label>
												<button
													onclick={() => removeNav(tKey, i)}
													class="text-subtext0 hover:text-red"
													aria-label="Remove"
												>
													<IconTrash size={14} />
												</button>
											</div>
										{/each}
									</div>
								</div>
							{/each}
						{:else if section.id === 'brand'}
							<div class="grid grid-cols-2 gap-3">
								<label class="col-span-2 block">
									<span class="text-subtext0 mb-1 block text-xs">Copyright name</span>
									<input
										type="text"
										bind:value={data.brand.copyrightName}
										class="admin-input"
									/>
								</label>
								<label class="col-span-2 block">
									<span class="text-subtext0 mb-1 block text-xs">Repo URL</span>
									<input type="url" bind:value={data.brand.repoUrl} class="admin-input" />
								</label>
								<label class="col-span-2 block">
									<span class="text-subtext0 mb-1 block text-xs">Commit base URL</span>
									<input
										type="url"
										bind:value={data.brand.commitBaseUrl}
										class="admin-input"
									/>
								</label>
								<label class="col-span-2 block">
									<span class="text-subtext0 mb-1 block text-xs">Contact email</span>
									<input
										type="email"
										bind:value={data.brand.contactEmail}
										class="admin-input"
									/>
								</label>
								<label class="col-span-2 flex items-center gap-2 text-sm">
									<input type="checkbox" bind:checked={data.brand.analytics.enabled} />
									<span>Enable Abacus analytics</span>
								</label>
								{#if data.brand.analytics.enabled}
									<label class="col-span-2 block">
										<span class="text-subtext0 mb-1 block text-xs">Abacus instance URL</span>
										<input
											type="url"
											bind:value={data.brand.analytics.abacusInstance}
											class="admin-input"
										/>
									</label>
									<label class="block">
										<span class="text-subtext0 mb-1 block text-xs">Namespace</span>
										<input
											type="text"
											bind:value={data.brand.analytics.abacusNamespace}
											class="admin-input"
										/>
									</label>
									<label class="block">
										<span class="text-subtext0 mb-1 block text-xs">Key</span>
										<input
											type="text"
											bind:value={data.brand.analytics.abacusKey}
											class="admin-input"
										/>
									</label>
								{/if}
							</div>
						{/if}
					</div>
				{/if}
			</section>
		{/each}
	</div>

	<footer class="text-subtext0 mt-8 text-xs">
		Edits autosave to localStorage. Click <strong>Download site.ts</strong> when ready, then drop
		the file into <code class="text-accent">src/lib/config/site.ts</code>, commit, and push.
	</footer>
</div>

<style>
	:global(.admin-input) {
		width: 100%;
		background-color: var(--color-mantle);
		border: 1px solid var(--color-surface0);
		color: var(--color-text);
		border-radius: 0.375rem;
		padding: 0.4rem 0.6rem;
		font-size: 0.875rem;
		font-family: inherit;
	}
	:global(.admin-input:focus) {
		outline: none;
		border-color: var(--current-accent-color);
	}
</style>
