// Generated by sync-pics.ts — do not edit manually
// Reset to empty; run scripts/sync-pics.ts (after pointing it at your own bucket)
// to repopulate, or commit images to /static/pics/ and write a local sync script.

interface ExifData {
	camera: string | null;
	aperture: number | null;
	shutterSpeed: string | null;
	iso: number | null;
	focalLength: number | null;
	dateTaken: string | null;
}

interface ImageVariant {
	width: number;
	format: 'webp' | 'jpeg';
	url: string;
	original?: boolean;
	size?: number;
}

interface ManifestEntry {
	id: string;
	hash: string;
	originalWidth: number;
	originalHeight: number;
	alt: string;
	exif: ExifData;
	variants: ImageVariant[];
}

interface Manifest {
	version: number;
	r2BaseUrl: string;
	images: ManifestEntry[];
}

const manifest: Manifest = {
	version: 1,
	r2BaseUrl: '',
	images: []
};

export default manifest;
